sudo: required
services:
 - docker

before_install:
 - docker build -t joerajeev/docker-multi-container-demo-client-test -f ./client/Dockerfile.dev ./client

script:
 - docker run joerajeev/docker-multi-container-demo-client-test npm test -- --coverage

after_success:
 - docker build -t joerajeev/docker-multi-container-demo-client ./client
 - docker build -t joerajeev/docker-multi-container-demo-nginx ./nginx
 - docker build -t joerajeev/docker-multi-container-demo-server ./server
 - docker build -t joerajeev/docker-multi-container-demo-worker ./worker
 # Log into docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
 #Push the images to docker hub
 - docker push joerajeev/docker-multi-container-demo-client
 - docker push joerajeev/docker-multi-container-demo-nginx
 - docker push joerajeev/docker-multi-container-demo-server
 - docker push joerajeev/docker-multi-container-demo-worker

deploy:
 provider: elasticbeanstalk
 region: ap-southeast-2
 app: multi-docker
 env: MultiDocker-env
 bucket_name: elasticbeanstalk-ap-southeast-2-515428563191
 bucket_path: docker-multi
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: $AWS_SECRET_KEY
